# Default Supabase Edge Function config
# See https://supabase.com/docs/guides/functions/config

[import_map]
# Add any necessary import map entries here if needed
# Example:
# imports = { "my-module" = "https://deno.land/x/my_module/mod.ts" }

[browser]
main = "index.ts"

[experimental_deploy_watch]
enabled = true
ignored_files = [".gitignore", "README.md"]

# Example: Enable JWT verification if needed for admin access
# [auth.jwt]
# enabled = true
# claim_mappings = ["user_id", "role"]
# required_claims = { "role": ["admin"] }